package Factura
// Generated 19 de febr. 2021, 12:15:29 by Hibernate Tools 5.2.12.Final
import java.math.BigDecimal
import java.util.HashSet

/**
 * Article generated by hbm2java
 */
class Article {
	var codA: String? = null
	var descrip: String? = null
	var preu: Float? = null
	var stock: Int? = null
	var stockMin: Int? = null
	var liniesFac: ArrayList<LiniaFac>? = arrayListOf<LiniaFac>()

	constructor() {}
	constructor(codA: String?) {
		this.codA = codA
	}

	constructor(
		codA: String?,
		descrip: String?,
		preu: Float?,
		stock: Int?,
		stockMin: Int?,
		liniesFac: ArrayList<LiniaFac>?
	) {
		this.codA = codA
		this.descrip = descrip
		this.preu = preu
		this.stock = stock
		this.stockMin = stockMin
		this.liniesFac = liniesFac
	}
}