package Factura
// Generated 19 de febr. 2021, 12:15:29 by Hibernate Tools 5.2.12.Final
import java.util.Date
import java.util.HashSet

/**
 * Factura generated by hbm2java
 */
class Factura {
	var numF: Int = 0
	var client: Client? = null
	var data: Date? = null
	var iva: Int? = null
	var liniesFac: ArrayList<LiniaFac>?  = arrayListOf<LiniaFac>()

	constructor() {}
	constructor(numF: Int, client: Client?) {
		this.numF = numF
		this.client = client
	}

	constructor(numF: Int, client: Client?, data: Date?, iva: Int?, liniesFac: ArrayList<LiniaFac>?) {
		this.numF = numF
		this.client = client
		this.data = data
		this.iva = iva
		this.liniesFac = liniesFac	}
}