package Factura
// Generated 19 de febr. 2021, 12:15:29 by Hibernate Tools 5.2.12.Final
import java.math.BigDecimal

/**
 * LiniaFac generated by hbm2java
 */
class LiniaFac {
	var numL: Int = 0
	var article: Article? = null
	var factura: Factura? = null
	var quant: Int? = null
	var preu: Float? = null

	constructor() {}
	constructor(numL: Int, article: Article?, factura: Factura?) {
		this.numL = numL
		this.article = article
		this.factura = factura
	}

	constructor(numL: Int, article: Article?, factura: Factura?, quant: Int?, preu: Float?) {
		this.numL = numL
		this.article = article
		this.factura = factura
		this.quant = quant
		this.preu = preu
	}
}