package Factura
// Generated 19 de febr. 2021, 12:15:29 by Hibernate Tools 5.2.12.Final
import java.util.HashSet

/**
 * Poble generated by hbm2java
 */
class Poble {
	var codPob: Int = 0
	var nom: String? = null
	var provincia: String? = null
	var clients: ArrayList<Client>?  = arrayListOf<Client>()

	constructor() {}
	constructor(codPob: Int) {
		this.codPob = codPob
	}

	constructor(codPob: Int, nom: String?, provincia: String?, clients: ArrayList<Client>?) {
		this.codPob = codPob
		this.nom = nom
		this.provincia = provincia
		this.clients = clients
	}
}