package classesGeoHib;
// Generated 19/02/2018 10:04:50 by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Comarca generated by hbm2java
 */
public class Comarca implements java.io.Serializable {

	private String nomC;
	private String provincia;
	private Set<Poblacio> poblacios = new HashSet<Poblacio>(0);

	public Comarca() {
	}

	public Comarca(String nomC) {
		this.nomC = nomC;
	}

	public Comarca(String nomC, String provincia, Set<Poblacio> poblacios) {
		this.nomC = nomC;
		this.provincia = provincia;
		this.poblacios = poblacios;
	}

	public String getNomC() {
		return this.nomC;
	}

	public void setNomC(String nomC) {
		this.nomC = nomC;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public Set<Poblacio> getPoblacios() {
		return this.poblacios;
	}

	public void setPoblacios(Set<Poblacio> poblacios) {
		this.poblacios = poblacios;
	}

}
