package classesGeoHib;
// Generated 19/02/2018 10:04:50 by Hibernate Tools 5.2.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Poblacio generated by hbm2java
 */
public class Poblacio implements java.io.Serializable {

	private int codM;
	private Comarca comarca;
	private String nom;
	private Integer poblacio;
	private BigDecimal extensio;
	private Short altura;
	private String longitud;
	private String latitud;
	private Character llengua;
	private Set<Institut> instituts = new HashSet<Institut>(0);

	public Poblacio() {
	}

	public Poblacio(int codM, String nom) {
		this.codM = codM;
		this.nom = nom;
	}

	public Poblacio(int codM, Comarca comarca, String nom, Integer poblacio, BigDecimal extensio, Short altura,
			String longitud, String latitud, Character llengua, Set<Institut> instituts) {
		this.codM = codM;
		this.comarca = comarca;
		this.nom = nom;
		this.poblacio = poblacio;
		this.extensio = extensio;
		this.altura = altura;
		this.longitud = longitud;
		this.latitud = latitud;
		this.llengua = llengua;
		this.instituts = instituts;
	}

	public int getCodM() {
		return this.codM;
	}

	public void setCodM(int codM) {
		this.codM = codM;
	}

	public Comarca getComarca() {
		return this.comarca;
	}

	public void setComarca(Comarca comarca) {
		this.comarca = comarca;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Integer getPoblacio() {
		return this.poblacio;
	}

	public void setPoblacio(Integer poblacio) {
		this.poblacio = poblacio;
	}

	public BigDecimal getExtensio() {
		return this.extensio;
	}

	public void setExtensio(BigDecimal extensio) {
		this.extensio = extensio;
	}

	public Short getAltura() {
		return this.altura;
	}

	public void setAltura(Short altura) {
		this.altura = altura;
	}

	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	public Character getLlengua() {
		return this.llengua;
	}

	public void setLlengua(Character llengua) {
		this.llengua = llengua;
	}

	public Set<Institut> getInstituts() {
		return this.instituts;
	}

	public void setInstituts(Set<Institut> instituts) {
		this.instituts = instituts;
	}

}
